### PR TITLE
Rebase repository

### PR DESCRIPTION
**Pull request by jpkrohling**
See #17 for context: if this looks good, I'll merge master and push it directly, as I'm sure squashing this PR will only cause more problems. For this case, we certainly want a proper rebase/merge.

### CODE REVIEW

**Comment by jpkrohling** [comment]
Image with this PR: quay.io/jpkroehling/jaeger-docker-protobuf:latest

**Comment by yurishkuro** [comment]
lgtm, but could you please describe the testing plan / steps.

**Comment by annanay25** [comment]
Thanks for this PR @jpkrohling! Could you please fix the conflicts? That will make it easier to review.

**Comment by jpkrohling** [comment]
> Thanks for this PR @jpkrohling! Could you please fix the conflicts? That will make it easier to review.

I don't think it's possible to fix it in a PR, but I'll try. The best would be to checkout this branch locally and run a `git diff master`.

**Comment by Falco20019** [comment]
> I don't think it's possible to fix it in a PR, but I'll try.

You should be able to fix it by merging master into this branch and solve the conflicts then.

**Comment by pavolloffay** [comment]
just FYI if somebody is interested I have built an image with this PR `pavolloffay/jaeger-docker-protobuf:PR18 `

**Comment by jpkrohling** [comment]
I'm closing this, as we'll probably not work on rebasing it this way.

**Pull request closed without merging**
